### ISSUE TITLE
Exception unhandled

### ISSUE THREAD

**Issue by irmeta** [OpenGamerTips/Neuron-API#4]
Managed Debugging Assistant 'BindingFailure' : 'The assembly with display name 'WRDMod' failed to load in the 'Load' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'WRDMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

**Comment by OpenGamerTips** [comment]
Yeah I forgot to make a deploy tutorial. It needs to be setup correctly to work.
Sorry for the late reply, I'm having to do a lot of schoolwork,

**Comment by irmeta** [comment]
Alright, thanks!
